sonar.projectKey=MiqueasAmorim_fc3.0-go-sonarcloud
sonar.organization=miqueasamorim
sonar.projectName=fc3.0-go-sonarcloud
sonar.projectVersion=1.0
sonar.sources=.
sonar.inclusions=**/*.go
sonar.exclusions=**/*_test.go,go.mod,go.sum,sonar-project.properties
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
